name: Publish Docker Image

on:
  push:
    branches:
      - main  # Jalankan workflow saat ada push ke branch main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/githubiot:latest .

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/githubiot:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/githubiot:latest
      
      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/githubiot"
          VERSION=${GITHUB_REF#refs/tags/} # Jika menjalankan dari tag, ambil versi

          # Jika push dari main branch, gunakan `latest`
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            VERSION="latest"
          fi

          docker build -t $IMAGE_NAME:$VERSION .
          docker push $IMAGE_NAME:$VERSION
